name: Hello World
description: This pair of steps will echo Hello world

inputs:
  echo_string:
    description: The string to echo.
    required: true

runs:
  using: composite

  steps:
    - name: Echo the input
      run: echo "${{ inputs.echo_string }}"
      shell: bash
