name: Workflow to dispatch

on:
  workflow_dispatch:
    inputs:
      echo_string:
        description: The string to echo.
        required: true
        type: string

jobs:
  sample:
    name: Sample echo
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: ./checkout
          repository: ${{ github.repository }}
          ref: refs/heads/main

#      - name: Echo the input
#        run: echo "${{ github.event.inputs.echo_string }}"

      - name: Echo the input
        uses: actions/hello-world@main
        with:
          echo_string: "${{ github.event.inputs.echo_string }}"
