name: Hello world

on:
  push:
    branches:
      - main

jobs:
  sample:
    name: Sample echo steps
    runs-on: ubuntu-20.04

    steps:
      - name: Echo Hello
        run: echo "Hello"

      - name: Echo World
        run: echo "World"

  script:
    name: "Run the hello-world.sh script"
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: ./checkout

      - name: Run script
        run: source ./checkout/scripts/hello-world.sh
