name: Hello world
concurrency:
  group: hw-${{ github.repository }}-${{ github.ref }}

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  ECHO_STRING: "Hello"

jobs:
  sample:
    name: Sample echo steps
    runs-on: ubuntu-20.04

    steps:
      - name: Echo Hello
        run: echo "${{ env.ECHO_STRING }}"

      - name: Echo World
        run: echo "World"

  script:
    name: "Run the hello-world.sh script"
    runs-on: ubuntu-20.04
    needs:
      - sample
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: ./checkout

      - name: Run script
        run: source ./checkout/scripts/hello-world.sh
